name: Publish
on:
  release:
    types: [published]
    
jobs:
  release:
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.0
          
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="DimUnits-$tag"
          
          # Build everything
          dotnet publish src/DimUnits/DimUnits -c Release -o -o "$release_name"
          
          tar czvf "${release_name}.tar.gz" "$release_name"
          
          rm -r "$release_name"
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "DimUnits*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}